<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>My Portofolio | Mila Nawa</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous" />

<!--bootstrap icons-->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">

    <!--MY CSS-->
    <link rel="stylesheet" href="style.css" />
  </head>
  <body id="home">

    <!-- NAVBAR -->
    <nav class="navbar navbar-expand-lg navbar-dark shadow-sm fixed-top" style="background-color: rgb(176, 122, 227)">
      <div class="container">
        <a class="navbar-brand" href="#">Mila Nawa</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav ms-auto">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="#home">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#about">About</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#Education">Education</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#Hobby">Hobby</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#Contact">Contact</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    <!-- AKHIR NAVBAR -->
    <!-- JUMBOTRON -->
    <section class="jumbotron text-center">
      <img src="img/4.png" alt="Siti Kamila Tunawa" width="300" class="img-thumbnail" />
      <h2 class="display-4">Siti Kamila Tunawa</h2>
      <p class="lead">Mahasiswa Universitas Qomaruddin</p>
      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1440 320">
        <path
          fill="#ffffff"
          fill-opacity="0.23"
          d="M0,128L40,128C80,128,160,128,240,112C320,96,400,64,480,64C560,64,640,96,720,96C800,96,880,64,960,58.7C1040,53,1120,75,1200,96C1280,117,1360,139,1400,149.3L1440,160L1440,320L1400,320C1360,320,1280,320,1200,320C1120,320,1040,320,960,320C880,320,800,320,720,320C640,320,560,320,480,320C400,320,320,320,240,320C160,320,80,320,40,320L0,320Z"
        ></path>
      </svg>
    </section>
    <!-- AKHIR JUMBOTRON -->
    <!-- ABOUT -->
    <section id="about">
      <div class="container">
        <div class="row text-center mb-3">
          <div class="col">
            <h2>About Me</h2>
          </div>
        </div>
        <div class="row text-center fs-5">
          <div class="col-12">
            <p>
          Hallo, perkenalkan nama saya Siti Kamila Tunawa bisa di panggil Mila saya adalah mahasiswa Universitas Qomaruddin Gresik saya memiliki keahlian di bidang jaringan dan terbiasa dengan pemecahan masalah yang ada di jaringan. saya terbiasa observasi lapangan untuk monitoring adanya kendala pada user baik secara daring maupun tatap muka
saya terbiasa belajar dan memahami proses pengolaan dan perawatan hardware IT
Memiliki Technical Thinking yang bagus, Bisa bekerja sama secara tim maupun mandiri
            </p>
          </div>
        </div>
      </div>
      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1440 320">
        <path
          fill="#5000ca"
          fill-opacity="0.25"
          d="M0,128L48,144C96,160,192,192,288,213.3C384,235,480,245,576,224C672,203,768,149,864,154.7C960,160,1056,224,1152,250.7C1248,277,1344,267,1392,261.3L1440,256L1440,320L1392,320C1344,320,1248,320,1152,320C1056,320,960,320,864,320C768,320,672,320,576,320C480,320,384,320,288,320C192,320,96,320,48,320L0,320Z"
        ></path>
      </svg>
    </section>
    <!-- AKHIR ABOUT -->
    <!-- Education -->
    <section id="Education">
      <div class="container">
        <div class="row text-center mb-5">
          <div class="col">
            <h2>Education</h2>
          </div>
        </div>
        <div class="row justify-content-center fs-5 text-center">
          <div class="col-3">
            <h3>SD</h3>
            <p>Saya bersekolah di SD Negri Mulyoagung II, Singgahan Tuban (Tahun 2008-2014)</p>
          </div>
          <div class="col-3">
          <h3>SMP</h3>
            <p>Saya bersekolah di SMP Negri 1 Singgahan Tuban (Tahun 2014-2017) </p>
          </div>
          <div class="col-3">
          <h3>SMK</h3>
            <p>Saya bersekolah di SMK Nurul Hidayah Perengkulon Gresik (Tahun 2017-2020)</p>
          </div>
          <div class="col-3">
          <h3>UNIVERSITAS</h3>
            <p>Saya berkuliah di Universitas Qomaruddin Gresik di Fakultas Teknik tepatnya di Prodi Teknik Informatika (Masuk Tahun 2020)</p>
          </div>
        </div>
      </div>
      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1440 320">
        <path
          fill="#5000ca"
          fill-opacity="0.18"
          d="M0,224L48,224C96,224,192,224,288,208C384,192,480,160,576,149.3C672,139,768,149,864,181.3C960,213,1056,267,1152,261.3C1248,256,1344,192,1392,160L1440,128L1440,320L1392,320C1344,320,1248,320,1152,320C1056,320,960,320,864,320C768,320,672,320,576,320C480,320,384,320,288,320C192,320,96,320,48,320L0,320Z"
        ></path>
      </svg>
    </section>

    <!-- AKHIR Education -->
    <!-- Hobby -->
    <section id="Hobby">
      <div class="container">
        <div class="row text-center">
          <div class="col">
            <h2>My Hobby</h2>
          </div>
        </div>
        <div class="row">
          <div class="col-4">
            <div class="card">
              <img src="img/2.jpg" class="card-img-top" alt="Hobby2" />
              <div class="card-body">
                <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
              </div>
            </div>
          </div>
          <div class="col-4">
            <div class="card">
              <img src="img/3.jpg" class="card-img-top" alt="Hobby3" />
              <div class="card-body">
                <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
              </div>
            </div>
          </div>
          <div class="col-4">
            <div class="card">
              <img src="img/2.jpg" class="card-img-top" alt="Hobby2" />
              <div class="card-body">
                <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
              </div>
            </div>
          </div>
        </div>
      </div>
      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1440 320"><path fill="#ffffff" fill-opacity="1" d="M0,64L48,69.3C96,75,192,85,288,85.3C384,85,480,75,576,90.7C672,107,768,149,864,144C960,139,1056,85,1152,64C1248,43,1344,53,1392,58.7L1440,64L1440,320L1392,320C1344,320,1248,320,1152,320C1056,320,960,320,864,320C768,320,672,320,576,320C480,320,384,320,288,320C192,320,96,320,48,320L0,320Z"></path></svg>
    </section>

    <!-- AKHIR Hobby -->

    <!--Contact-->
    <section id="Contact">
      <div class="container">
        <div class="row text-center mb-3">
          <div class="col">
            <h2>Contact Me</h2>
          </div>
        </div>
        <div class="row justify-content-center">
          <div class="col-md-6">
            <form>
              <div class="mb-3">
                <label for="exampleInputEmail1" class="form-label">Email</label>
                <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
              </div>
              <div class="mb-3">
                <label for="exampleInputname" class="form-label">Nama Lengkap</label>
                <input type="name" class="form-control" id="exampleInputname">
              </div>
              <div class="mb-3">
                <label for="pesan" class="form-label">Pesan</label>
                <textarea class="form-control" id="pesan" rows="3"></textarea>
              </div>
              <button type="kirim" class="btn btn-light">Kirim</button>
            </form>
          </div>
        </div>
        </div>
      </div>
    </section>
    <!--Akhir Contact-->
    <!--Footer-->
    <footer class="text-white text-center pb-3" style="background-color: rgb(169, 105, 228)">
      <p>Created with <i class="bi bi-heart-fill text-danger"></i> by<a href="https://instagram.com/nawaamila?igshid=ZDdkNTZiNTM= "class="text-white"> Mila Nawa</a></p>
      <p>Tanggal/Waktu: <span id="tanggalwaktu"></span></p>
<script>
var dt = new Date();
document.getElementById("tanggalwaktu").innerHTML = dt.toLocaleString();
</script>
    </footer>
   
    <!--Akhir footer-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></scrip>
  </body>
</html>
